group 'com.amap.flutter.map'
version '1.0'

buildscript {
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.5.3'
    }
}

rootProject.allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

apply plugin: 'com.android.library'

android {
    namespace "com.amap.flutter.map"
    compileSdkVersion 34

    defaultConfig {
        minSdkVersion 16
    }
    lintOptions {
        disable 'InvalidPackage'
    }
}

dependencies {
//    implementation 'com.amap.api:3dmap-location-search:10.1.600_loc6.5.1_sea9.7.4'
    compileOnly files('libs/AMap3DMap_11.1.063.aar')
}

